project:
  type: website
  output-dir: docs


website:
  title: "Bruprosjekt"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: false

execute:
  echo: false       # Don't show code in output
  warning: false
  error: false
  message: false

