project:
  type: website
  output-dir: docs


website:
  title: "Bruprosjekt"
  search: false
  
  sidebar:
    position: right
    style: "floating"
    contents:
      - text: Resultater
        href: index.qmd
      - text: Informasjon
        href: informasjon.qmd

format: 
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    toc-location: right
    toc-depth: 4
    toc-title: Innhold

execute:
  echo: false       # Don't show code in output
  warning: false
  error: false
  message: false

